######################################
# DEV Environment Configuration
######################################
environment=DEV
api.base.url=https://dev-api.example.com
mongodb.connection.string=mongodb://dev-mongo:27017
mongodb.database=dev_test_automation
android.app.path=src/test/resources/apps/dev-android-app.apk
ios.app.path=src/test/resources/apps/dev-ios-app.app
