######################################
# PROD Environment Configuration
######################################
environment=PROD
api.base.url=https://api.example.com
mongodb.connection.string=mongodb://prod-mongo:27017
mongodb.database=prod_test_automation
android.app.path=src/test/resources/apps/prod-android-app.apk
ios.app.path=src/test/resources/apps/prod-ios-app.app
