######################################
# QA Environment Configuration
######################################
environment=QA
api.base.url=https://qa-api.example.com
mongodb.connection.string=mongodb://qa-mongo:27017
mongodb.database=qa_test_automation
android.app.path=src/test/resources/apps/SauceLabs-MyDemoApp.apk
ios.app.path=src/test/resources/apps/qa-ios-app.app
