######################################
# STAGE Environment Configuration
######################################
environment=STAGE
api.base.url=https://stage-api.example.com
mongodb.connection.string=mongodb://stage-mongo:27017
mongodb.database=stage_test_automation
android.app.path=src/test/resources/apps/stage-android-app.apk
ios.app.path=src/test/resources/apps/stage-ios-app.app
